---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/digital_ai_howto/Testapp
  type: udm.Application
  children:
  - name: !format Applications/digitial_ai_howto/Testapp/%version%
    type: udm.DeploymentPackage
    deployables:
    - name: hello-py-deploy.yaml
      type: k8s.ResourcesFile
      fileEncodings:
        ".+\\.properties": ISO-8859-1
      mergePatchType: strategic
      propagationPolicy: Foreground
      updateMethod: apply
      createOrder: "60"
      modifyOrder: "50"
      destroyOrder: "40"
      displayResourceOnLogs: "false"
      showContainerLogs: "false"
      bytesToReadFromContainerLogs: "4000"
      file: !file "../kubernetes/hello-python.yaml"
